---
language: python
python:
- 2.7
script:
- molecule lint
- molecule destroy
- molecule dependency
- molecule syntax
- molecule create
- molecule prepare
- molecule converge
- travis_wait 20 molecule idempotence
- molecule side_effect
- molecule verify
- molecule destroy
