---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: parallels
lint:
  name: yamllint
  enabled: False
platforms:
  - name: instance
    box: ubuntu-18.04
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    provision: false
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
  playbooks:
    converge: ../../site.yml
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8