---
- name: Configure zabbix server
  hosts: zabbix_server
  become: yes
  roles:
  - { role: ANXS.postgresql }
  - { role: dj-wasabi.zabbix-server }
  vars_files:
  - "{{inventory_dir}}/play_vars/zabbix-server.yml"

- name: Configure zabbix agent
  hosts: all
  become: yes
  roles:
  - { role: dj-wasabi.zabbix-agent }

- name: Create hosts, groups and templates on zabbix server
  hosts: all
  become: yes
  roles:
  - { role: dj-wasabi.zabbix-agent, become: no, tags: ['api'] }
  serial: 1
  vars_files:
  - "{{inventory_dir}}/play_vars/zabbix-api.yml"
